# Daten simulieren

In [12]:
import numpy

N = 10
alter = numpy.random.randint(18,100, size=N)
km = numpy.random.randint(0,500_000, size=N)
einkommen = numpy.random.randint(15, 151, size=N) * 1000

In [18]:
km

array([ 96690,  18574, 219250, 358756, 497950, 403297, 486893, 352648,
       327239, 209657])

In [17]:
km[0]

np.int64(96690)

In [19]:
kaufverhalten = []
for i in range(0,N):
    if km[i] > 200_000:
        kauf = 1
    else:
        kauf = 0
    kaufverhalten.append( kauf )

In [20]:
kaufverhalten

[0, 0, 1, 1, 1, 1, 1, 1, 1, 1]

In [36]:
import numpy
import pandas


# 1. Kundenfeatures simulieren
N = 100
alter = numpy.random.randint(18,100, size=N)
km = numpy.random.randint(0,500_000, size=N)
einkommen = numpy.random.randint(15, 151, size=N) * 1000

# 2. Kaufverhalten simulieren
kaufverhalten = []
for i in range(0,N):
    if km[i] > 200_000:
        kauf = 1
    else:
        kauf = 0
    kaufverhalten.append( kauf )

# 3. Eine Tabelle erstellen
d = {"Alter"     : alter,
     "km"        : km,
     "Einkommen" : einkommen,
     "Kauf"      : kaufverhalten}
df = pandas.DataFrame(d)
df

    Alter      km  Einkommen  Kauf
0      80   19179      83000     0
1      95    5986     123000     0
2      37  395638     137000     1
3      24  389305      75000     1
4      34  456898      44000     1
..    ...     ...        ...   ...
95     67  168506     139000     0
96     82  278661     123000     1
97     52   76727     122000     0
98     19  235760      80000     1
99     95  476755      77000     1

[100 rows x 4 columns]

In [23]:
type(df)

pandas.DataFrame

In [26]:
df["Alter"]

0    67
1    95
2    92
3    47
4    64
5    30
6    29
7    77
8    65
9    78
Name: Alter, dtype: int64

In [27]:
type(df["Alter"])

pandas.Series

In [28]:
df.loc[2]

Alter            92
km            74556
Einkommen    111000
Kauf              0
Name: 2, dtype: int64

In [29]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [31]:
df["Alter"].mean()

np.float64(64.4)

In [32]:
df.to_csv("unsere_kunden.csv", index=False)

# Daten fürs ML vorbereiten

In [33]:
import sklearn

In [42]:
df

    Alter      km  Einkommen  Kauf
0      80   19179      83000     0
1      95    5986     123000     0
2      37  395638     137000     1
3      24  389305      75000     1
4      34  456898      44000     1
..    ...     ...        ...   ...
95     67  168506     139000     0
96     82  278661     123000     1
97     52   76727     122000     0
98     19  235760      80000     1
99     95  476755      77000     1

[100 rows x 4 columns]

In [62]:
x = df[ ["Alter", "km", "Einkommen"] ]
y = df[ ["Kauf"] ]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,
                                          test_size=0.2)

In [63]:
x.shape

(100, 3)

In [64]:
y.shape

(100, 1)

In [65]:
x_train.shape

(80, 3)

In [66]:
y_train.shape

(80, 1)

In [67]:
x_test.shape

(20, 3)

In [68]:
y_test.shape

(20, 1)

# Ein ML Modell bauen

In [69]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model = model.fit(x_train, y_train)

In [73]:
model.predict(x_test)

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1])

In [76]:
y_test["Kauf"].values

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1])

# Das Modell visualisieren

In [82]:
from sklearn.tree import export_text
txt = export_text(model, feature_names=x_train.columns)
print(txt)

|--- km <= 203881.00
|   |--- class: 0
|--- km >  203881.00
|   |--- class: 1

In [81]:
x_train.columns

Index(['Alter', 'km', 'Einkommen'], dtype='str')

# Alles in einer Zelle

In [18]:
import numpy
import pandas

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import export_text

# 1. Kundenfeatures simulieren
N = 1000
alter = numpy.random.randint(18,100, size=N)
km = numpy.random.randint(0,500_000, size=N)
einkommen = numpy.random.randint(15, 151, size=N) * 1000

# 2. Kaufverhalten simulieren
kaufverhalten = []
for i in range(0,N):
    if km[i] > 210_000 and einkommen[i] > 80_000:
        if numpy.random.randint(1,7) <= 2:
            kauf = 0
        else:
            kauf = 1
    else:
        kauf = 0
    kaufverhalten.append( kauf )

# 3. Eine Tabelle erstellen
d = {"Alter"     : alter,
     "km"        : km,
     "Einkommen" : einkommen,
     "Kauf"      : kaufverhalten}
df = pandas.DataFrame(d)

# 4. Daten fürs ML vorbereiten

# 4.1 Was ist Input x? Was ist Output y?
x = df[ ["Alter", "km", "Einkommen"] ]
y = df[ ["Kauf"] ]

# 4.2 Train-Test-Split
x_train, x_test, y_train, y_test = train_test_split(x,y,
                                          test_size=0.2)

# 5. Einen DecisionTree (DT) bauen
model = DecisionTreeClassifier()
model = model.fit(x_train, y_train)

# 6. Das Modell visualisieyren
txt = export_text(model, feature_names=x_train.columns)
print(txt)

|--- Einkommen <= 80500.00
|   |--- class: 0
|--- Einkommen >  80500.00
|   |--- km <= 210375.50
|   |   |--- class: 0
|   |--- km >  210375.50
|   |   |--- Alter <= 33.50
|   |   |   |--- km <= 254750.50
|   |   |   |   |--- Einkommen <= 111000.00
|   |   |   |   |   |--- Einkommen <= 105500.00
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- Einkommen >  105500.00
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- Einkommen >  111000.00
|   |   |   |   |   |--- class: 1
|   |   |   |--- km >  254750.50
|   |   |   |   |--- Einkommen <= 138000.00
|   |   |   |   |   |--- km <= 308088.50
|   |   |   |   |   |   |--- km <= 274669.00
|   |   |   |   |   |   |   |--- km <= 263430.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- km >  263430.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- km >  274669.00
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- km >  308088.50
|   |   |   |   |   |   |--- Einkommen <= 125500.00
|   |   |   |   |   |   |   |--- Einkommen <= 113000.00
|   |   |   |   |   |   |   |   |--- Alter <= 25.50
|   |   |   |   |   |   |   |   |   |--- Alter <= 22.50
|   |   |   |   |   |   |   |   |   |   |--- Alter <= 19.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- Alter >  19.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- Alter >  22.50
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- Alter >  25.50
|   |   |   |   |   |   |   |   |   |--- km <= 466416.50
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- km >  466416.50
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- Einkommen >  113000.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- Einkommen >  125500.00
|   |   |   |   |   |   |   |--- Einkommen <= 133000.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- Einkommen >  133000.00
|   |   |   |   |   |   |   |   |--- km <= 370109.00
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- km >  370109.00
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- Einkommen >  138000.00
|   |   |   |   |   |--- class: 0
|   |   |--- Alter >  33.50
|   |   |   |--- km <= 226394.50
|   |   |   |   |--- Alter <= 67.00
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- Alter >  67.00
|   |   |   |   |   |--- Alter <= 80.00
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- Alter >  80.00
|   |   |   |   |   |   |--- class: 0
|   |   |   |--- km >  226394.50
|   |   |   |   |--- Alter <= 96.50
|   |   |   |   |   |--- Einkommen <= 142500.00
|   |   |   |   |   |   |--- Einkommen <= 125500.00
|   |   |   |   |   |   |   |--- Alter <= 90.50
|   |   |   |   |   |   |   |   |--- km <= 467022.00
|   |   |   |   |   |   |   |   |   |--- km <= 456260.50
|   |   |   |   |   |   |   |   |   |   |--- km <= 426674.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 11
|   |   |   |   |   |   |   |   |   |   |--- km >  426674.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- km >  456260.50
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- km >  467022.00
|   |   |   |   |   |   |   |   |   |--- Einkommen <= 88500.00
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- Einkommen >  88500.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- Alter >  90.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- Einkommen >  125500.00
|   |   |   |   |   |   |   |--- km <= 457808.00
|   |   |   |   |   |   |   |   |--- Einkommen <= 127500.00
|   |   |   |   |   |   |   |   |   |--- Alter <= 80.00
|   |   |   |   |   |   |   |   |   |   |--- Alter <= 64.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- Alter >  64.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- Alter >  80.00
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- Einkommen >  127500.00
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- km >  457808.00
|   |   |   |   |   |   |   |   |--- km <= 462078.00
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- km >  462078.00
|   |   |   |   |   |   |   |   |   |--- Alter <= 86.50
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- Alter >  86.50
|   |   |   |   |   |   |   |   |   |   |--- km <= 488479.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |   |--- km >  488479.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- Einkommen >  142500.00
|   |   |   |   |   |   |--- Einkommen <= 145500.00
|   |   |   |   |   |   |   |--- Alter <= 71.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- Alter >  71.00
|   |   |   |   |   |   |   |   |--- Alter <= 78.50
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- Alter >  78.50
|   |   |   |   |   |   |   |   |   |--- km <= 446193.00
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- km >  446193.00
|   |   |   |   |   |   |   |   |   |   |--- Alter <= 94.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- Alter >  94.00
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- Einkommen >  145500.00
|   |   |   |   |   |   |   |--- Alter <= 62.00
|   |   |   |   |   |   |   |   |--- km <= 257662.00
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- km >  257662.00
|   |   |   |   |   |   |   |   |   |--- km <= 305455.50
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- km >  305455.50
|   |   |   |   |   |   |   |   |   |   |--- km <= 384393.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |   |--- km >  384393.50
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- Alter >  62.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- Alter >  96.50
|   |   |   |   |   |--- Einkommen <= 117000.00
|   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- Einkommen >  117000.00
|   |   |   |   |   |   |--- class: 0