# Datensatz runterladen und einlesen

In [4]:
import kagglehub
import pandas

path = kagglehub.dataset_download("wspirat/germany-used-cars-dataset-2023")
df = pandas.read_csv(f"{path}/data.csv")
df

,Unnamed: 0,brand,model,color,registration_date,year,price_in_euro,power_kw,power_ps,transmission_type,fuel_type,fuel_consumption_l_100km,fuel_consumption_g_km,mileage_in_km,offer_description
0,0,alfa-romeo,Alfa Romeo GTV,red,10/1995,1995,1300,148,201,Manual,Petrol,"10,9 l/100 km",260 g/km,160500.0,2.0 V6 TB
1,1,alfa-romeo,Alfa Romeo 164,black,02/1995,1995,24900,191,260,Manual,Petrol,NaN,- (g/km),190000.0,"Q4 Allrad, 3.2L GTA"
2,2,alfa-romeo,Alfa Romeo Spider,black,02/1995,1995,5900,110,150,Unknown,Petrol,NaN,- (g/km),129000.0,ALFA ROME 916
3,3,alfa-romeo,Alfa Romeo Spider,black,07/1995,1995,4900,110,150,Manual,Petrol,"9,5 l/100 km",225 g/km,189500.0,2.0 16V Twin Spark L
4,4,alfa-romeo,Alfa Romeo 164,red,11/1996,1996,17950,132,179,Manual,Petrol,"7,2 l/100 km",- (g/km),96127.0,"3.0i Super V6, absoluter Topzustand !"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251074,251074,volvo,Volvo XC40,white,04/2023,2023,57990,192,261,Automatic,Hybrid,NaN,43 km Reichweite,1229.0,Plus Bright T5 Recharge Intellisafe*Surround+P...
251075,251075,volvo,Volvo XC90,white,03/2023,2023,89690,173,235,Automatic,Diesel,"7,6 l/100 km",202 g/km,4900.0,B5 AWD Diesel Ultimate Dark 7-Sitzer Massage F...
251076,251076,volvo,Volvo V60,white,05/2023,2023,61521,145,197,Automatic,Diesel,"4,7 l/100 km",125 g/km,1531.0,"B4 D Plus Dark 145 kW, 5-türig (Diesel)"
251077,251077,volvo,Volvo XC40,white,05/2023,2023,57890,132,179,Automatic,Hybrid,NaN,45 km Reichweite,1500.0,T5 Recharge Plus Dark *Standh*360°*beh.Lenk
251078,251078,volvo,Volvo XC40,gold,03/2023,2023,52900,160,218,Automatic,Electric,NaN,438 km Reichweite,50.0,Ultimate Recharge Twin Motor AHK GJR

# Datensatz explorieren

In [9]:
df.sample(100)

,Unnamed: 0,brand,model,color,registration_date,year,price_in_euro,power_kw,power_ps,transmission_type,fuel_type,fuel_consumption_l_100km,fuel_consumption_g_km,mileage_in_km,offer_description
31972,31972,bmw,BMW 116,blue,10/2014,2014,16000,100,136,Manual,Petrol,"5,6 l/100 km",133 g/km,44300.0,i 1 Lim. 116i Urban BiXenon Navi 1 Hand
34401,34401,bmw,BMW 220,blue,01/2016,2016,18877,140,190,Automatic,Diesel,"4,3 l/100 km",113 g/km,106980.0,"M-Sport*Navi,LED,AHK,HIFI,SHZ"
163052,163052,peugeot,Peugeot Boxer,white,07/2021,2021,25573,121,165,Manual,Diesel,"6,4 l/100 km",169 g/km,84050.0,"2,2 165 *L4H2* Premium KLIMA+ KAMERA+ NAVI"
191558,191558,skoda,Skoda Roomster,black,04/2015,2015,9449,66,90,Manual,Diesel,"4,7 l/100 km",- (g/km),109000.0,1.6 TDI DPF Fresh
80513,80513,hyundai,Hyundai i30,blue,11/2019,2019,30000,202,275,Manual,Petrol,"7,8 l/100 km",- (g/km),24000.0,i30 2.0 T-GDI N Performance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5814,5814,audi,Audi A6,black,03/2011,2011,13000,150,204,Automatic,Diesel,"5,1 l/100 km",140 g/km,250000.0,A6 3.0 TDI DPF multitronic
185736,185736,seat,SEAT Arona,black,04/2021,2021,15490,66,90,Manual,CNG,"3,4 kg/100 km",93 g/km,10628.0,1.0 TGI XCELLENCE NAVI LED ACC 5J.-GARANTIE
19526,19526,audi,Audi Q3,white,02/2020,2020,28990,110,150,Automatic,Petrol,"5,9 l/100 km",154 g/km,51000.0,35 TFSI S tronic advanced CarPlay/ACC/Virtual
15129,15129,audi,Audi SQ5,grey,08/2018,2018,43900,260,354,Automatic,Petrol,NaN,- (g/km),51200.0,"3.0 TFSI tiptronic quattro*LED*Pano*21""*"
22817,22817,audi,Audi S3,white,05/2023,2023,49950,228,310,Automatic,Petrol,8 l/100 km,182 g/km,10.0,Sportback+Sofort Verfügbar+

In [10]:
df.iloc[15129]

Unnamed: 0                                                     15129
brand                                                           audi
model                                                       Audi SQ5
color                                                           grey
registration_date                                            08/2018
year                                                            2018
price_in_euro                                                  43900
power_kw                                                         260
power_ps                                                         354
transmission_type                                          Automatic
fuel_type                                                     Petrol
fuel_consumption_l_100km                                         NaN
fuel_consumption_g_km                                       - (g/km)
mileage_in_km                                                51200.0
offer_description           3.0 TFSI tiptronic quattro*LED*Pano*21"*
Name: 15129, dtype: object

In [13]:
d = {"A" : [100,200,300],
     "B" : [104, 43, 45]}
t = pandas.DataFrame(d,
                     index=["Augsburg", "Kempten", "München"] )
t

            A    B
Augsburg  100  104
Kempten   200   43
München   300   45

In [12]:
t.index

RangeIndex(start=0, stop=3, step=1)

In [15]:
t.loc[ ["Kempten", "Augsburg"] ]

            A    B
Kempten   200   43
Augsburg  100  104

In [17]:
t.iloc[  [0,2] ]

            A    B
Augsburg  100  104
München   300   45

In [18]:
t

            A    B
Augsburg  100  104
Kempten   200   43
München   300   45

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 251079 entries, 0 to 251078
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Unnamed: 0                251079 non-null  int64
 1   brand                     251079 non-null  str
 2   model                     251079 non-null  str
 3   color                     250913 non-null  str
 4   registration_date         251075 non-null  str
 5   year                      251079 non-null  str
 6   price_in_euro             251079 non-null  str
 7   power_kw                  250945 non-null  str
 8   power_ps                  250950 non-null  str
 9   transmission_type         251079 non-null  str
 10  fuel_type                 251079 non-null  str
 11  fuel_consumption_l_100km  224206 non-null  str
 12  fuel_consumption_g_km     251079 non-null  str
 13  mileage_in_km             250927 non-null  float64
 14  offer_description         251078 non-null  str
dtypes: float64(1), int64(1), str(13)
memory usage: 55.8 MB

In [36]:
d = {"A" : [100,200,300],
     "B" : [104, "55r", 45]}
t = pandas.DataFrame(d,
                     index=["Augsburg", "Kempten", "München"] )
t

            A    B
Augsburg  100  104
Kempten   200  55r
München   300   45

In [37]:
t.info()

<class 'pandas.DataFrame'>
Index: 3 entries, Augsburg to München
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      object
dtypes: int64(1), object(1)
memory usage: 95.0+ bytes

In [35]:
pandas.__version__

'3.0.5'

In [45]:
df["price_in_euro"] = pandas.to_numeric(df["price_in_euro"],
                                        errors="coerce")

In [46]:
df.iloc[2400]

Unnamed: 0                                  2400
brand                                       audi
model                                    Audi A4
color                                       grey
registration_date                         Manual
year                                      Petrol
price_in_euro                                NaN
power_kw                            7,8 l/100 km
power_ps                                      75
transmission_type                         Manual
fuel_type                                07/2004
fuel_consumption_l_100km                187 g/km
fuel_consumption_g_km                       2004
mileage_in_km                             2460.0
offer_description           Avant 1.6 *TÜV 09/23
Name: 2400, dtype: object

In [40]:
float("435344")

435344.0

In [41]:
float("3e4")

30000.0

In [42]:
float(" KLIMAUTOMATIK*")

ValueError: could not convert string to float: ' KLIMAUTOMATIK*'

# Boolean Indexing

In [47]:
t

            A    B
Augsburg  100  104
Kempten   200  55r
München   300   45

In [49]:
t["A"][ [True,False,True] ]

Augsburg    100
München     300
Name: A, dtype: int64

In [50]:
import kagglehub
import pandas

path = kagglehub.dataset_download("wspirat/germany-used-cars-dataset-2023")
df = pandas.read_csv(f"{path}/data.csv")
df["price_in_euro"] = pandas.to_numeric(df["price_in_euro"],
                                        errors="coerce")

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 251079 entries, 0 to 251078
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Unnamed: 0                251079 non-null  int64
 1   brand                     251079 non-null  str
 2   model                     251079 non-null  str
 3   color                     250913 non-null  str
 4   registration_date         251075 non-null  str
 5   year                      251079 non-null  str
 6   price_in_euro             250880 non-null  float64
 7   power_kw                  250945 non-null  str
 8   power_ps                  250950 non-null  str
 9   transmission_type         251079 non-null  str
 10  fuel_type                 251079 non-null  str
 11  fuel_consumption_l_100km  224206 non-null  str
 12  fuel_consumption_g_km     251079 non-null  str
 13  mileage_in_km             250927 non-null  float64
 14  offer_description         251078 non-null  str
dtypes: float64(2), int64(1), str(12)
memory usage: 54.7 MB

In [52]:
df["price_in_euro"].isna()

0         False
1         False
2         False
3         False
4         False
          ...
251074    False
251075    False
251076    False
251077    False
251078    False
Name: price_in_euro, Length: 251079, dtype: bool

In [53]:
df_raw = pandas.read_csv(f"{path}/data.csv")

fehlerhaft = df["price_in_euro"].isna()
df_raw["price_in_euro"][ fehlerhaft ]

2400                KLIMAAUTOMATIK*
2743                      Automatik
5297                         6-Gang
9616       XEN AAC SHZ FSP APS 5TRG
12206        NAVplus LEDER PANO ALC
                    ...
241462                     Navi uvm
242569                          PDC
242579            Beats-Soundsystem
246113                          SHZ
247366                  MATTSCHWARZ
Name: price_in_euro, Length: 199, dtype: str

# Alles in einer Codezelle

In [54]:
df.columns

Index(['Unnamed: 0', 'brand', 'model', 'color', 'registration_date', 'year',
       'price_in_euro', 'power_kw', 'power_ps', 'transmission_type',
       'fuel_type', 'fuel_consumption_l_100km', 'fuel_consumption_g_km',
       'mileage_in_km', 'offer_description'],
      dtype='str')

In [2]:
import kagglehub
import pandas

# 1. Datensatz runterladen und einlesen
path = kagglehub.dataset_download("wspirat/germany-used-cars-dataset-2023")
df_raw = pandas.read_csv(f"{path}/data.csv")

# 2. Bereinigung der Daten
df_clean = df_raw[ ["mileage_in_km", "power_ps", "price_in_euro"] ].copy()
df_clean["price_in_euro"] = pandas.to_numeric(df_clean["price_in_euro"],
                                              errors="coerce")
df_clean

        mileage_in_km power_ps  price_in_euro
0            160500.0      201         1300.0
1            190000.0      260        24900.0
2            129000.0      150         5900.0
3            189500.0      150         4900.0
4             96127.0      179        17950.0
...               ...      ...            ...
251074         1229.0      261        57990.0
251075         4900.0      235        89690.0
251076         1531.0      197        61521.0
251077         1500.0      179        57890.0
251078           50.0      218        52900.0

[251079 rows x 3 columns]